<?php

namespace Database\Seeders;

use App\Models\Tenant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TenantSeeder extends Seeder
{
    public function run(): void
    {
        $tenants = [
            [
                'first_name'     => 'Maria',
                'last_name'      => 'Santos',
                'email'          => 'maria.santos@example.com',
                'contact_number' => '09171234501',
                'room_number'    => '203',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-10',
                'move_out_date'  => '2026-11-10',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Sofia',
                'last_name'      => 'Reyes',
                'email'          => 'sofia.reyes@example.com',
                'contact_number' => '09171234502',
                'room_number'    => '203',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-15',
                'move_out_date'  => '2026-11-15',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Ana',
                'last_name'      => 'Cruz',
                'email'          => 'ana.cruz@example.com',
                'contact_number' => '09171234503',
                'room_number'    => '203',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-01',
                'move_out_date'  => '2026-12-01',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Elena',
                'last_name'      => 'Bautista',
                'email'          => 'elena.bautista@example.com',
                'contact_number' => '09171234504',
                'room_number'    => '204',
                'floor'          => 2,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2025-10-28',
                'move_out_date'  => '2026-06-29',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Liza',
                'last_name'      => 'Garcia',
                'email'          => 'liza.garcia@example.com',
                'contact_number' => '09171234505',
                'room_number'    => '206',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-05',
                'move_out_date'  => '2026-12-05',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Grace',
                'last_name'      => 'Dela Cruz',
                'email'          => 'grace.delacruz@example.com',
                'contact_number' => '09181234501',
                'room_number'    => '301',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-02',
                'move_out_date'  => '2026-11-02',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Jenny',
                'last_name'      => 'Villanueva',
                'email'          => 'jenny.villanueva@example.com',
                'contact_number' => '09181234502',
                'room_number'    => '301',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-08',
                'move_out_date'  => '2026-11-08',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Chloe',
                'last_name'      => 'Mendoza',
                'email'          => 'chloe.mendoza@example.com',
                'contact_number' => '09181234503',
                'room_number'    => '302',
                'floor'          => 3,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2025-11-20',
                'move_out_date'  => '2026-11-20',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Claire',
                'last_name'      => 'Aquino',
                'email'          => 'claire.aquino@example.com',
                'contact_number' => '09181234504',
                'room_number'    => '303',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-01',
                'move_out_date'  => '2026-12-01',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Mia',
                'last_name'      => 'Torres',
                'email'          => 'mia.torres@example.com',
                'contact_number' => '09181234505',
                'room_number'    => '303',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-10',
                'move_out_date'  => '2026-12-10',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Patricia',
                'last_name'      => 'Ramos',
                'email'          => 'patricia.ramos@example.com',
                'contact_number' => '09181234506',
                'room_number'    => '303',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-10-30',
                'move_out_date'  => '2026-07-15',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Camila',
                'last_name'      => 'Soriano',
                'email'          => 'camila.soriano@example.com',
                'contact_number' => '09181234507',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-25',
                'move_out_date'  => '2026-11-25',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Diana',
                'last_name'      => 'Castillo',
                'email'          => 'diana.castillo@example.com',
                'contact_number' => '09181234508',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-12',
                'move_out_date'  => '2026-12-12',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Isabella',
                'last_name'      => 'Navarro',
                'email'          => 'isabella.navarro@example.com',
                'contact_number' => '09181234509',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-05',
                'move_out_date'  => '2026-11-05',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Sophia',
                'last_name'      => 'Flores',
                'email'          => 'sophia.flores@example.com',
                'contact_number' => '09181234510',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-15',
                'move_out_date'  => '2026-12-15',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Gabriela',
                'last_name'      => 'Pascual',
                'email'          => 'gabriela.pascual@example.com',
                'contact_number' => '09181234511',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-18',
                'move_out_date'  => '2026-11-18',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Isabel',
                'last_name'      => 'Gonzales',
                'email'          => 'isabel.gonzales@example.com',
                'contact_number' => '09191234501',
                'room_number'    => '401',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-10-26',
                'move_out_date'  => '2026-10-26',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Olivia',
                'last_name'      => 'Hernandez',
                'email'          => 'olivia.hernandez@example.com',
                'contact_number' => '09191234502',
                'room_number'    => '401',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-03',
                'move_out_date'  => '2026-11-03',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Nicole',
                'last_name'      => 'Magno',
                'email'          => 'nicole.magno@example.com',
                'contact_number' => '09191234503',
                'room_number'    => '402',
                'floor'          => 4,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2025-11-12',
                'move_out_date'  => '2026-11-12',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Emily',
                'last_name'      => 'Salazar',
                'email'          => 'emily.salazar@example.com',
                'contact_number' => '09191234504',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-22',
                'move_out_date'  => '2026-11-22',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Camille',
                'last_name'      => 'Dizon',
                'email'          => 'camille.dizon@example.com',
                'contact_number' => '09191234505',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-02',
                'move_out_date'  => '2026-12-02',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Jessica',
                'last_name'      => 'Reyes',
                'email'          => 'jessica.reyes@example.com',
                'contact_number' => '09191234506',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-08',
                'move_out_date'  => '2026-12-08',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Angelica',
                'last_name'      => 'Luna',
                'email'          => 'angelica.luna@example.com',
                'contact_number' => '09191234507',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-14',
                'move_out_date'  => '2026-11-14',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Samantha',
                'last_name'      => 'Buenaventura',
                'email'          => 'samantha.buenaventura@example.com',
                'contact_number' => '09191234508',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-18',
                'move_out_date'  => '2026-12-18',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Trisha',
                'last_name'      => 'Enriquez',
                'email'          => 'trisha.enriquez@example.com',
                'contact_number' => '09191234509',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-10-29',
                'move_out_date'  => '2026-10-29',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Alyssa',
                'last_name'      => 'Santiago',
                'email'          => 'alyssa.santiago@example.com',
                'contact_number' => '09191234510',
                'room_number'    => '405',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-20',
                'move_out_date'  => '2026-12-20',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Kristine',
                'last_name'      => 'Domingo',
                'email'          => 'kristine.domingo@example.com',
                'contact_number' => '09191234511',
                'room_number'    => '405',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-28',
                'move_out_date'  => '2026-11-28',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Rachel',
                'last_name'      => 'Aguilar',
                'email'          => 'rachel.aguilar@example.com',
                'contact_number' => '09191234512',
                'room_number'    => '405',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-22',
                'move_out_date'  => '2026-12-22',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Vanessa',
                'last_name'      => 'Manaloto',
                'email'          => 'vanessa.manaloto@example.com',
                'contact_number' => '09201234501',
                'room_number'    => '501',
                'floor'          => 5,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2025-11-01',
                'move_out_date'  => '2026-11-01',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Hazel',
                'last_name'      => 'Ocampo',
                'email'          => 'hazel.ocampo@example.com',
                'contact_number' => '09201234502',
                'room_number'    => '502',
                'floor'          => 5,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2025-11-09',
                'move_out_date'  => '2026-11-09',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Maricel',
                'last_name'      => 'Padilla',
                'email'          => 'maricel.padilla@example.com',
                'contact_number' => '09201234503',
                'room_number'    => '503',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-16',
                'move_out_date'  => '2026-11-16',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Angela',
                'last_name'      => 'Tolentino',
                'email'          => 'angela.tolentino@example.com',
                'contact_number' => '09201234504',
                'room_number'    => '503',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-04',
                'move_out_date'  => '2026-12-04',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Roxanne',
                'last_name'      => 'Medina',
                'email'          => 'roxanne.medina@example.com',
                'contact_number' => '09201234505',
                'room_number'    => '503',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-11',
                'move_out_date'  => '2026-12-11',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Evelyn',
                'last_name'      => 'Valdez',
                'email'          => 'evelyn.valdez@example.com',
                'contact_number' => '09201234506',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-10-31',
                'move_out_date'  => '2026-10-31',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Sheila',
                'last_name'      => 'Mercado',
                'email'          => 'sheila.mercado@example.com',
                'contact_number' => '09201234507',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-19',
                'move_out_date'  => '2026-11-19',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Clarissa',
                'last_name'      => 'Macaraeg',
                'email'          => 'clarissa.macaraeg@example.com',
                'contact_number' => '09201234508',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-14',
                'move_out_date'  => '2026-12-14',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Elaine',
                'last_name'      => 'Espiritu',
                'email'          => 'elaine.espiritu@example.com',
                'contact_number' => '09201234509',
                'room_number'    => '506',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-11-24',
                'move_out_date'  => '2026-11-24',
                'status'         => 'active',
            ],
            [
                'first_name'     => 'Joy',
                'last_name'      => 'Ybanez',
                'email'          => 'joy.ybanez@example.com',
                'contact_number' => '09201234510',
                'room_number'    => '506',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2025-12-19',
                'move_out_date'  => '2026-12-19',
                'status'         => 'active',
            ],
        ];

        foreach ($tenants as $data) {
            $tempPassword = Tenant::generateTempPassword();

            Tenant::create([
                'account_id'       => Tenant::generateAccountId(),
                'password_hash'    => Hash::make($tempPassword),
                'is_temp_password' => true,
                'first_name'       => $data['first_name'],
                'last_name'        => $data['last_name'],
                'email'            => $data['email'],
                'contact_number'   => $data['contact_number'],
                'profile_photo'    => null,
                'room_number'      => $data['room_number'],
                'floor'            => $data['floor'],
                'stay_type'        => $data['stay_type'],
                'move_in_date'     => $data['move_in_date'],
                'move_out_date'    => $data['move_out_date'],
                'status'           => $data['status'],
                'is_active'        => true,
                'last_login_at'    => null,
                'notes'            => null,
            ]);
        }
    }
}