<?php

namespace Database\Seeders;

use App\Models\Tenant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TenantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Total: 38 tenants
     *   Floor 2 →  5 tenants
     *   Floor 3 → 11 tenants
     *   Floor 4 → 12 tenants
     *   Floor 5 → 10 tenants
     */
    public function run(): void
    {
        $tenants = [

            // ----------------------------------------------------------------
            // FLOOR 2 — 5 tenants (rooms 201–205)
            // ----------------------------------------------------------------
            [
                'first_name'     => 'Maria',
                'last_name'      => 'Santos',
                'email'          => 'maria.santos@example.com',
                'contact_number' => '09171234501',
                'room_number'    => '201',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-01-15',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Jose',
                'last_name'      => 'Reyes',
                'email'          => 'jose.reyes@example.com',
                'contact_number' => '09171234502',
                'room_number'    => '201',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Ana',
                'last_name'      => 'Cruz',
                'email'          => 'ana.cruz@example.com',
                'contact_number' => '09171234503',
                'room_number'    => '201',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Carlo',
                'last_name'      => 'Bautista',
                'email'          => 'carlo.bautista@example.com',
                'contact_number' => '09171234504',
                'room_number'    => '202',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Liza',
                'last_name'      => 'Garcia',
                'email'          => 'liza.garcia@example.com',
                'contact_number' => '09171234505',
                'room_number'    => '202',
                'floor'          => 2,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-15',
                'status'         => 'pending',
            ],

            // ----------------------------------------------------------------
            // FLOOR 3 — 11 tenants (rooms 301–311)
            // ----------------------------------------------------------------
            [
                'first_name'     => 'Mark',
                'last_name'      => 'Dela Cruz',
                'email'          => 'mark.delacruz@example.com',
                'contact_number' => '09181234501',
                'room_number'    => '301',
                'floor'          => 3,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-01-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Jenny',
                'last_name'      => 'Villanueva',
                'email'          => 'jenny.villanueva@example.com',
                'contact_number' => '09181234502',
                'room_number'    => '302',
                'floor'          => 3,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-01-20',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Ryan',
                'last_name'      => 'Mendoza',
                'email'          => 'ryan.mendoza@example.com',
                'contact_number' => '09181234503',
                'room_number'    => '303',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-05',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Claire',
                'last_name'      => 'Aquino',
                'email'          => 'claire.aquino@example.com',
                'contact_number' => '09181234504',
                'room_number'    => '303',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-15',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Miguel',
                'last_name'      => 'Torres',
                'email'          => 'miguel.torres@example.com',
                'contact_number' => '09181234505',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-02-20',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Patricia',
                'last_name'      => 'Ramos',
                'email'          => 'patricia.ramos@example.com',
                'contact_number' => '09181234506',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-03-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Kevin',
                'last_name'      => 'Soriano',
                'email'          => 'kevin.soriano@example.com',
                'contact_number' => '09181234507',
                'room_number'    => '304',
                'floor'          => 3,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-03-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Diana',
                'last_name'      => 'Castillo',
                'email'          => 'diana.castillo@example.com',
                'contact_number' => '09181234508',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-20',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Aaron',
                'last_name'      => 'Navarro',
                'email'          => 'aaron.navarro@example.com',
                'contact_number' => '09181234509',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-04-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Sophia',
                'last_name'      => 'Flores',
                'email'          => 'sophia.flores@example.com',
                'contact_number' => '09181234510',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-04-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Nathan',
                'last_name'      => 'Pascual',
                'email'          => 'nathan.pascual@example.com',
                'contact_number' => '09181234511',
                'room_number'    => '305',
                'floor'          => 3,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-04-15',
                'status'         => 'pending',
            ],

            // ----------------------------------------------------------------
            // FLOOR 4 — 12 tenants (rooms 401–412)
            // ----------------------------------------------------------------
            [
                'first_name'     => 'Isabel',
                'last_name'      => 'Gonzales',
                'email'          => 'isabel.gonzales@example.com',
                'contact_number' => '09191234501',
                'room_number'    => '401',
                'floor'          => 4,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-01-05',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Rafael',
                'last_name'      => 'Hernandez',
                'email'          => 'rafael.hernandez@example.com',
                'contact_number' => '09191234502',
                'room_number'    => '402',
                'floor'          => 4,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-01-15',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Nicole',
                'last_name'      => 'Magno',
                'email'          => 'nicole.magno@example.com',
                'contact_number' => '09191234503',
                'room_number'    => '402',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-01-25',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Erick',
                'last_name'      => 'Salazar',
                'email'          => 'erick.salazar@example.com',
                'contact_number' => '09191234504',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-02-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Camille',
                'last_name'      => 'Dizon',
                'email'          => 'camille.dizon@example.com',
                'contact_number' => '09191234505',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Jerome',
                'last_name'      => 'Reyes',
                'email'          => 'jerome.reyes@example.com',
                'contact_number' => '09191234506',
                'room_number'    => '403',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-20',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Angelica',
                'last_name'      => 'Luna',
                'email'          => 'angelica.luna@example.com',
                'contact_number' => '09191234507',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-03-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Dennis',
                'last_name'      => 'Buenaventura',
                'email'          => 'dennis.buenaventura@example.com',
                'contact_number' => '09191234508',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-10',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Trisha',
                'last_name'      => 'Enriquez',
                'email'          => 'trisha.enriquez@example.com',
                'contact_number' => '09191234509',
                'room_number'    => '404',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-20',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Alvin',
                'last_name'      => 'Santiago',
                'email'          => 'alvin.santiago@example.com',
                'contact_number' => '09191234510',
                'room_number'    => '405',
                'floor'          => 4,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-04-01',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Kristine',
                'last_name'      => 'Domingo',
                'email'          => 'kristine.domingo@example.com',
                'contact_number' => '09191234511',
                'room_number'    => '405',
                'floor'          => 4,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-04-05',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Ronald',
                'last_name'      => 'Aguilar',
                'email'          => 'ronald.aguilar@example.com',
                'contact_number' => '09191234512',
                'room_number'    => '406',
                'floor'          => 4,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-04-15',
                'status'         => 'pending',
            ],

            // ----------------------------------------------------------------
            // FLOOR 5 — 10 tenants (rooms 501–510)
            // ----------------------------------------------------------------
            [
                'first_name'     => 'Vanessa',
                'last_name'      => 'Manaloto',
                'email'          => 'vanessa.manaloto@example.com',
                'contact_number' => '09201234501',
                'room_number'    => '501',
                'floor'          => 5,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-01-08',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Bernard',
                'last_name'      => 'Ocampo',
                'email'          => 'bernard.ocampo@example.com',
                'contact_number' => '09201234502',
                'room_number'    => '502',
                'floor'          => 5,
                'stay_type'      => 'Solo Room',
                'move_in_date'   => '2024-01-18',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Maricel',
                'last_name'      => 'Padilla',
                'email'          => 'maricel.padilla@example.com',
                'contact_number' => '09201234503',
                'room_number'    => '503',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-03',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Gilbert',
                'last_name'      => 'Tolentino',
                'email'          => 'gilbert.tolentino@example.com',
                'contact_number' => '09201234504',
                'room_number'    => '503',
                'floor'          => 5,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-02-12',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Roxanne',
                'last_name'      => 'Medina',
                'email'          => 'roxanne.medina@example.com',
                'contact_number' => '09201234505',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-02-22',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Harold',
                'last_name'      => 'Valdez',
                'email'          => 'harold.valdez@example.com',
                'contact_number' => '09201234506',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-05',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Sheila',
                'last_name'      => 'Mercado',
                'email'          => 'sheila.mercado@example.com',
                'contact_number' => '09201234507',
                'room_number'    => '504',
                'floor'          => 5,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-03-15',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Joselito',
                'last_name'      => 'Macaraeg',
                'email'          => 'joselito.macaraeg@example.com',
                'contact_number' => '09201234508',
                'room_number'    => '505',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-03-25',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Elaine',
                'last_name'      => 'Espiritu',
                'email'          => 'elaine.espiritu@example.com',
                'contact_number' => '09201234509',
                'room_number'    => '505',
                'floor'          => 5,
                'stay_type'      => 'Shared Room',
                'move_in_date'   => '2024-04-02',
                'status'         => 'pending',
            ],
            [
                'first_name'     => 'Aldrin',
                'last_name'      => 'Ybañez',
                'email'          => 'aldrin.ybanez@example.com',
                'contact_number' => '09201234510',
                'room_number'    => '505',
                'floor'          => 5,
                'stay_type'      => 'Bed Spacer',
                'move_in_date'   => '2024-04-12',
                'status'         => 'pending',
            ],
        ];

        foreach ($tenants as $data) {
            $tempPassword = Tenant::generateTempPassword();

            Tenant::create([
                'account_id'       => Tenant::generateAccountId(),
                'password_hash'    => \Illuminate\Support\Facades\Hash::make($tempPassword),
                'is_temp_password' => true,
                'first_name'       => $data['first_name'],
                'last_name'        => $data['last_name'],
                'email'            => $data['email'],
                'contact_number'   => $data['contact_number'],
                'profile_photo'    => null,
                'room_number'      => $data['room_number'],
                'floor'            => $data['floor'],
                'stay_type'        => $data['stay_type'],
                'move_in_date'     => $data['move_in_date'],
                'move_out_date'    => null,
                'status'           => $data['status'],
                'is_active'        => true,
                'last_login_at'    => null,
                'notes'            => null,
            ]);
        }
    }
}
